# Generated by Django 5.0.7 on 2024-07-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='posts')),
                ('body', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('view', models.IntegerField(default=0)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('direction', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('post', 'POST'), ('article', 'ARTICLE'), ('vacancy', 'VACANCY'), ('case', 'CASE')], default='article', max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='posts')),
                ('body', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('view', models.IntegerField(default=0)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=150)),
                ('condition', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('archived', 'ARCHIVED')], default='active', max_length=250)),
                ('type', models.CharField(choices=[('post', 'POST'), ('article', 'ARTICLE'), ('vacancy', 'VACANCY'), ('case', 'CASE')], default='case', max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='logos')),
                ('about', models.TextField()),
                ('skills', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('general', 'GENERAL'), ('premium', 'PREMIUM')], default='general', max_length=250)),
                ('rating', models.IntegerField(default=0)),
                ('case', models.CharField(max_length=100)),
                ('vacancy', models.CharField(max_length=250)),
                ('chat', models.CharField(max_length=250)),
                ('target', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='posts')),
                ('body', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('view', models.IntegerField(default=0)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('post', 'POST'), ('article', 'ARTICLE'), ('vacancy', 'VACANCY'), ('case', 'CASE')], default='post', max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='posts')),
                ('body', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('view', models.IntegerField(default=0)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=150)),
                ('requirements', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('archived', 'ARCHIVED')], default='active', max_length=250)),
                ('type', models.CharField(choices=[('post', 'POST'), ('article', 'ARTICLE'), ('vacancy', 'VACANCY'), ('case', 'CASE')], default='vacancy', max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
